---
title: "Raster-to-Polygon"
author: "Anna Talucci"
date: "5/5/2021"
output: html_document
---

# Overview






# Clear workspace

```{r}
rm(list=ls()) 
```

# Packages

```{r include=FALSE}
library(sp)
library(sf)
library(rgdal) # geospatial data
library(raster)
library(rgeos) # GIS Geometry
library(foreign) # deals with dbf files
```

# Projection
[BC Albers Equal Area projection](https://georepository.com/crs_3005/NAD83-BC-Albers.html)

https://epsg.io/3005 or https://spatialreference.org/ref/epsg/3005/

```{r}
ea_bc = "+proj=aea +lat_1=50 +lat_2=58.5 +lat_0=45 +lon_0=-126 +x_0=1000000 +y_0=0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs"
```

# Read in raster
```{r}
tw_rdnbr = raster("../data/rdnbr/TW_rdnbr.tif")
```

# Read in Shapefile
```{r}
tw_perm = readOGR("../data/perimeters/tw_R10252_2013_Forestonly.shp", "tw_R10252_2013_Forestonly") 
```

# Reproject in Equal area

```{r}
tw_perm_ea = spTransform(tw_perm, CRS(ea_bc))
```


# Clip raster to polygon
```{r}
tw_clip <- mask(tw_rdnbr, tw_perm_ea)
```

```{r}
plot(tw_clip)
plot(tw_perm_ea, add=TRUE)
```

# Convert raster to polygon

```{r}
tw_rdnbr_poly = rasterToPolygons(tw_clip, fun=NULL, n=4, na.rm=TRUE, digits=12, dissolve=FALSE)

```

```{r}
plot(tw_rdnbr_poly)
```

```{r}
tw_rdnbr_sf = st_as_sf(tw_rdnbr_poly)
```

#  Write to shapefile

```{r}
st_write(tw_rdnbr_sf, "../outputs/tw_rdnnbr_poly.shp", driver="ESRI Shapefile") 
```